services:
  frontend:
    image: dadandan/quirknotes_frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile_frontend
      target: frontend
    environment:
      - ENV=Docker

  backend:
    image: dadandan/quirknotes_backend:latest
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
    environment:
      - ENV=Docker
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"